--onlybook fixed.

diff --git a/howto b/howto
--- a/howto
+++ b/howto
@@ -1,24 +1,20 @@
 #!/bin/bash
 
-# Exit if no arguments are supplied, nothing to do.
-if [ $# -eq 0 ] ; then
-        displayhelp
-        exit 1
-fi
-
-# Declare book name in ${books} array, e.g. books=( "mybook" "git" )
+# Declare book name in 'books' array under the "## Books ##" section, e.g. books=( "mybook" "git" )
 # Then create a file in ~/.common-configs/ using the naming convention: howto.mybook
 #
-# So the above should be:
+# So the above example points to these files:
 #   ~/.common-configs/howto.mybook
 #   ~/.common-configs/howto.git
 
 ## Books ##
 books=( "void" "term" )
 
+
 # VARIABLES
 n=$#
 numbooks=${#books[@]}
+debug_howto=false
 onlybook=false
 allbooks=false
 legacy=false
@@ -46,28 +42,54 @@ displayhelp() {
 }
 
 readbook() {
-	echo
 	for n do {
                 # Escape if we run out of arguments.
-                if [ $# -eq 0 ] ; then
-                        exit 0
-                fi
+		checkargs "$@"
+		if [ "$debug_howto" == true ] ; then
+			echo "   readbook():           Args: $@"
+			echo "   readbook():            Arg: $1"
+			echo "   readbook():   Book file is: $book"
+			echo
+		fi
 		# Find supplied argument (keyword) in book and display.
                 grep -i "$1" "$book" | while read -r line
                 do
                         if [ "$1" == '' ] ; then
+				echo "$1 not found in $book, it might be in another file or not present,"
+				echo "you can either add it or use ':' to print all entries of that file."
                                 break
                         fi
+			echo
                         echo -e "\033[36m——————————————————————————————————\033[0m"
                         line=$(printf '%b\n' "$( echo -e "$line" | sed ''/": "/s//:`printf "\033[1;36m——————————————————————————————————\033[0m"`/'' | sed 's/——————————————————————————————————/\n——————————————————————————————————\n/' )")
-                        echo -e "$line\n\n"
+                        echo -e "$line\n"
                 done
                 shift
+		# If no option was specified, run in freeform mode (i.e legacy).
+		# This calls the usebook() function again to check whether the next argument is a book name.
+                if [ "$legacy" == true ] ; then
+			checkargs "$@"
+                        usebook "$@"
+                fi
 	} done
 }
 
 checkargs() {
-	# Check if we have remaining arguments to use as search strings in readbook().
+	# When expected that we have run out of arguments after readbook() it means that we're done and should exit.
+	if [ $# -eq 0 ] ; then
+		echo
+		exit 0
+	fi
+}
+
+checknoargs() {
+	# If using --debug, then display argument count.
+	if [ "$debug_howto" == true ] ; then
+		echo "checknoargs(): Number of args: $#"
+		echo "checknoargs():           Args: $@"
+		echo
+	fi
+	# Check if we do not have remaining arguments to use as search strings in readbook().
 	if [ $# -eq 0 ] ; then
 		echo -e "Error: No arguments supplied after book."
                 displayhelp
@@ -76,26 +98,32 @@ checkargs() {
 }
 
 usebook() {
-#	if [ "$allbooks" == true ] ; then
-#	fi
-
+	# Test whether the argument is in the 'books' array, then sets the book file as the specified book,
+	# Otherwise, use the howto.main book file, /home/$USER/.common-configs/howto.main.
 	if [[ "${books[@]}" =~ "$1" ]] ; then
 		book="/home/$USER/.common-configs/howto.$1"
 		shift
-		checkargs
-		readbook "$@"
+	elif [ -r "/home/$USER/.common-configs/howto.$1" ] ; then
+		echo "File '/home/$USER/.common-configs/howto.$1' exists, but $1 isn't configured in the 'books' array inside of this script."
+		echo "Please add it in order for the --allbooks feature to work."
+		book="/home/$USER/.common-configs/howto.$1"
+		shift
 	else
-		if test -f $book ; then
-			echo "File '$book' exists, but isn't configured in the 'books' array."
-			echo "Please add it in order for the --allbooks feature to work."
-			book="/home/$USER/.common-configs/howto.$1"
-			shift
-			checkargs
-			readbook "$@"
-		else
-			
+		book="/home/$USER/.common-configs/howto.main"
+		if [ "$onlybook" == true ] ; then
+			echo
+			echo "Specified book '$1' does not exist, using $book by default."
+			echo "If you've intended to use $book, there is no need to specify -o or --onlybook."
 		fi
 	fi
+        # If using --debug, then display arguments and 'book' (book file).
+        if [ "$debug_howto" == true ] ; then
+                echo "    usebook():   Book file is: $book"
+                echo "    usebook():           Args: $@"
+		echo
+        fi
+	checknoargs "$@"
+	readbook "$@"
 }
 
 displaybooks() {
@@ -138,6 +166,12 @@ runlegacy() {
 	} done
 }
 
+# Exit if no arguments are supplied, nothing to do.
+if [ $# -eq 0 ] ; then
+        displayhelp
+        exit 1
+fi
+
 while [ ! "$#" -eq 0 ]
 do
 	case "$1" in
@@ -145,6 +179,11 @@ do
 			displayhelp # Call the displayhelp function.
 			exit 0
 			;;
+                -d|--debug) # Enable debug messages.
+                        debug_howto=true
+                        shift
+			echo
+                        ;;
 		-n|--nocolor) # Don't use colors with script output.
 			nocolor # Call the nocolor function.
 			shift
@@ -154,11 +193,17 @@ do
 			exit 0
 			;;
 		-o|--onlybook) # Only search in specific book.
-			shift
-			book="/home/$USER/.common-configs/howto.$1"
-			onlybook=true
-			shift
-			readbook "$@"
+			if [[ "${books[@]}" =~ "$2" ]] ; then
+				if [ ! -r "/home/$USER/.common-configs/howto.$2" ] ; then
+					echo "File '/home/$USER/.common-configs/howto.$2' does not exist or isn't readable."
+					exit 1
+				fi
+				shift
+				book="/home/$USER/.common-configs/howto.$1"
+				shift
+				checknoargs "$@"
+				readbook "$@"
+			fi
 			exit 0
 			;;
 		-a|--allbooks) # Search all books simultaneously for provided string.
